create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  task_id text not null,
  device_id text not null,
  session_name text not null default '',
  event_type text not null check (
    event_type in (
      'task_completed',
      'task_waiting_for_input',
      'task_idle_too_long',
      'agent_disconnected'
    )
  ),
  title text not null,
  body text not null,
  dedupe_key text not null,
  read_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_read_created_idx
  on public.notifications (user_id, read_at, created_at desc);

create index if not exists notifications_user_dedupe_created_idx
  on public.notifications (user_id, dedupe_key, created_at desc);
